# Generated by Django 4.1.1 on 2022-10-03 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web_dashboard_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Portfolio', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(web_dashboard_api.models.get_parked_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSelection',
            fields=[
                ('id', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('companies', models.ForeignKey(db_column='stock_symbol', on_delete=django.db.models.deletion.DO_NOTHING, to='web_dashboard_api.companies')),
                ('portfolio', models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='web_dashboard_api.portfolio')),
            ],
        ),
    ]
