# Generated by Django 4.0.7 on 2022-12-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_dashboard_api', '0003_alter_portfolio_user'),
        ('web_dashboard_api', '0004_portfolioselection_allocation'),
    ]

    operations = [
    ]
