# Generated by Django 4.0.7 on 2022-12-06 00:35

from django.conf import settings
from django.db import migrations, models
import web_dashboard_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_dashboard_api', '0005_merge_20221204_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(web_dashboard_api.models.get_parked_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
